config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :categories
  devise_for :users
  root "home#index"
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end


# root "categories#index"

# get '/categories' => 'categories#index'
# get '/categories/new' => 'categories#new', as: 'new_category'
# post '/categories' => 'categories#create', as: 'create_category'
# get '/categories/:id' => 'categories#show', as: 'category'
# get '/categories/:id/edit' => 'categories#edit', as: 'edit_category'
# patch '/categories/:id' => 'categories#update'
# delete '/categories/:id' => 'categories#destroy', as: 'delete_category'

# get '/tasks' => 'tasks#index'
# get '/tasks/new' => 'tasks#new', as: 'new_task'
# post '/tasks' => 'tasks#create', as: 'create_task'
# get '/tasks/:id' => 'tasks#show', as: 'task'
# get '/tasks/:id/edit' => 'tasks#edit', as: 'edit_task'
# patch '/tasks/:id' => 'tasks#update'
# delete '/tasks/:id' => 'tasks#destroy', as: 'delete_task'

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    belongs_to :user
    has_many :tasks

    scope :by_user, lambda { |user| 
        where(:user_id => user.id)
    }
end

app/models/task.rb
class Task < ApplicationRecord
    validates :category_id, :title, :body, presence: true
    belongs_to :category

    # scope :by_user, lambda { |user| 
    #     where(:user_id => user.id)
    # }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :categories, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :set_tasks

  # GET /categories or /categories.json
  def index
    # @categories = Category.all
    @categories = Category.by_user(current_user)
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    @category.user = current_user

    respond_to do |format|
      if @category.save
        format.html { redirect_to root_path, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to root_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.by_user(current_user).find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:title)
    end

    def set_tasks 
      @tasks = Task.order(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    
  def index
    if user_signed_in?
    @categories = Category.by_user(current_user).pluck(:id)
    @tasks = Task.includes(:category).where(category_id: @categories)
    @task_id = Task.includes(:category).where(category_id: @categories).pluck(:category_id)
    @categories_tasks = Category.find(@task_id)
    end
  end
end


app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_categories
 
  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_path, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to root_path, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  # tasks_url

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:title, :body, :category_id)
    end

    def set_categories 
      @categories = Category.by_user(current_user).all.order(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <h2 class="mb-5 ">
    <strong>Category:</strong>
    <%= category.title %>
  </h2>

  <% category.tasks.each do |task|%>
    <p>
    <%= task.title %> | <%= link_to "View Task", task, class: "text-decoration-none"%>
    </p>
  <% end %>



</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li class="list-unstyled"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="card position-absolute top-50 start-50 translate-middle" style="height: 25rem; width: 25rem">
<div class="position-absolute top-50 start-50 translate-middle" style="height: 15rem; width: 15rem; text-align: center;">
  <div>
    <%= form.label :title, style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :title %>
  </div>

  <div class="mt-2">
    <%= form.submit %>
  </div>
  </div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>

 

  <div class="card position-absolute top-50 start-50 translate-middle text-white bg-dark" style="height: 25rem; width: 25rem;">
  <div class="position-absolute top-50 start-50 translate-middle" >
   <h1>Categories</h1>
    <ul>
      <% @categories.each do |category| %>
      <li class=""><%=link_to category.title, category, class:" text-decoration-none text-white link-danger " %></li>
      <% end %>
    </ul>
    </div>
  </div>

app/views/categories/new.html.erb
<div  style="text-align: center; margin-top: 3rem;">
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to home", root_path, class:"text-decoration-none" %>
</div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="card position-absolute top-50 start-50 translate-middle text-white bg-dark" style="height: 25rem; width: 25rem;">
 <div class="position-absolute top-50 start-50 translate-middle " style="width: 20rem; " >
  <%= render @category %>
  <%= link_to "Edit this category", edit_category_path(@category), class: "text-decoration-none d-block mt-5 " %> 
  <%= link_to "Back to home", root_path, class: "text-decoration-none" %>

  <% if @category.tasks.length != 0 %>
 
  <% else %>
  
  <%= button_to "Destroy this category", @category, method: :delete, class: "btn btn-danger" %>
  <p class="text-danger">All the tasks in this category are completed</p>
  <% end %>

 </div>
</div>

app/views/home/index.html.erb
<% if user_signed_in? %>


<div class="mt-5">
<h1 class="d-inline ">TODO List</h1>
<p class="d-inline ms-2 fw-bolder"><%=link_to "Create New Category", new_category_path, class:"text-dark text-decoration-none link-primary" %></p> 
<p class="d-inline ms-2 fw-bolder"><%=link_to "Create New Task", new_task_path, class:"text-dark text-decoration-none link-primary" %></p>
<table class="table table-striped table-hover table-light">
  <thead>
    <tr class="bg-dark text-dark">
      <th scope="col"><%= link_to "Category", categories_path, class: "text-decoration-none text-dark link-primary" %></th>
      <th scope="col">Task</th>
      <th scope="col">Description</th>
   
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
        <% @categories_tasks.each do |catta|%>
            <% if catta.id == task.category_id %>
            <tr>
                <td><%=link_to catta.title, catta, class:"text-dark text-decoration-none link-primary fw-bold text-uppercase" %></td>
                <td><%= task.title %></td>
                <td><%= task.body %></td>
         
                <td>
                <%= button_to "Delete", task_path(task.id) , method: :delete, class:"btn btn-danger d-inline-block mb-1", style:"width: 35%; font-size: 12px;"%>
                <%= link_to "Edit", edit_task_path(task.id), class:"btn btn-danger d-inline-block mb-1", style:"width: 35%; font-size: 12px;" %>
                <%= link_to "View", task_path(task.id), class:"btn btn-danger d-block ", style:"width: 35%; font-size: 12px;" %>
                </td>
            </tr>
            <% else %>
          
            <% end %>
        <% end %>
    <% end %>
   
  </tbody>
  </div>
  <% else%>
    <div class="card position-absolute top-50 start-50 translate-middle text-white bg-dark" style="width: 25rem; height: 20rem;">

    
      <h1 class="text-center my-5">Welcome to your Wonderful Planner!</h1>

      <div class="card-body bg-black text-center pb-4">
      <h5 class="card-title text-white">Planner</h5>
      <p class="card-text text-white">What are you working on today?</p>

      <%= link_to "Sign Up!", new_user_registration_path, class: "btn btn-light me-2 " %> 
  
      <%= link_to "Login", new_user_session_path, class: "btn btn-light" %>
      </div>
    </div>
  <% end %>
  <%= @set_category %> 
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>


    <%= render "partials/navbar"%>
    <div class="container">
    <%= yield %>
    </div>

     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
<h3><%= link_to "Planner", root_path, class:"text-white text-decoration-none ms-3 link-primary" %></h3>
<% if current_user %>
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active " aria-current="page" >Hello <span class="fw-bold"><%= current_user.email.split("@")[0].upcase%></span> !</a>
        </li>
      </ul>
      <div class="d-flex" role="search">
        <%= link_to "Sign Out", destroy_user_session_path, 'data-turbo-method': :delete, class:"btn btn-outline-light" %>
       
        <% else %>
        <div class="collapse navbar-collapse">
        </div>
        <%= link_to "Sign Up!", new_user_registration_path, class:"btn btn-outline-light me-2 " %> 
  
        <%= link_to "Login", new_user_session_path, class:"btn btn-outline-light " %>
        
        <% end %>
      </div>
    </div>
  </div>
</nav>



app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red; margin: auto; width: 50%;">
      <ul>
        <% task.errors.each do |error| %>
          <li class="list-unstyled fw-bold text-uppercase"><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="card position-absolute top-50 start-50 translate-middle" style="height: 25rem; width: 25rem">

<div class="position-absolute top-50 start-50 translate-middle" style="height: 15rem; width: 15rem; text-align: center;">
  <div>
    <%= form.label :title, style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block; font-weight:bold; text-transform: uppercase;" %>
    <%= form.text_field :body %>
  </div>

  <div class="mt-2">
  <%= form.label :category, style:"display: block; font-weight:bold; text-transform: uppercase;" %>
  <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.title, cat.id]}) %>
  
  </div>

  <div class="mt-2">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong  >Title:</strong>
    <%= task.title%>
  </p>

  <p>
  <strong>Category:</strong>
    <%= link_to task.category.title, task.category %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= task.body %>
  </p>

</div>

app/views/tasks/edit.html.erb
<div  style="text-align: center; margin-top: 3rem;">
<h1>Editing task</h1>


<%= render "form", task: @task, class: "mt-2" %>

<br>

<div >
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to home", root_path %>

</div>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks" >
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<div  style="text-align: center; margin-top: 3rem;">
<h1>New task</h1>
<% if @categories.length == 0 %>
  <p class="text-danger fw-bold">Create Category First</p>
<% end%>
<%= render "form", task: @task %>
<%= link_to "Back to home", root_path, class:"text-decoration-none" %>
<br>


</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="card position-absolute top-50 start-50 translate-middle text-white bg-dark" style="height: 25rem; width: 25rem;">
 <div class="position-absolute top-50 start-50 translate-middle " style="width: 20rem; " >
  <%= render @task %>
  <%= link_to "Edit this task", edit_task_path(@task), class: "d-block" %>
  <%= link_to "Back to home", root_path %>

  <%= button_to "Destroy this task", @task, method: :delete, class: "btn btn-warning mt-2" %>
</div>
</div>